name: swrly
description: Async data-fetching and server-state cache for Flutter, inspired by TanStack Query and SWR.
version: 0.0.1
homepage: https://github.com/redhotsixbull/swrly
repository: https://github.com/redhotsixbull/swrly
issue_tracker: https://github.com/redhotsixbull/swrly/issues

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
